### PR TITLE
Parallel measure extraction

### PR DESCRIPTION
**Pull request by zhangfanmark**
Hi Lauren, 

I have updated wm_measure_all_subjects.py to enable parallel computation, considering the number of clusters and the number of subjects can be large. Also the changes will address Saba's problems I think. Just saw the email.

I also updated tract_measurement.py to sort the measurement files. Otherwise, it may generate mismatch error to the demographics file when doing the statistics. This happened to the dataset I am working now. glob.glob somehow did not output the files ordered by file names. Not sure if this would break you previous analysis.

Regards,
Fan

### CODE REVIEW

**Comment by ljod** [comment]
Yes I meant to add that sorting but did not get to it. 

Parallel is reasonable, but I don't understand how it could fix Saba's problem. I don't think you want it to go into subdirectories recursively looking for data to measure, but that is what would be needed? I'm confused.

**Comment by zhangfanmark** [comment]
Sorry I misunderstood the problem. Before wm_measure_all_subjects assumes the subject is under a folder XXX_reg_reg, but outlier_removal generates XXX_reg_reg_outlier_removed. I updated this part as well. I thought Saba's problem was due to this.

**Comment by ljod** [comment]
Oh okay. I see. I haven't yet used your script to measure all subjects. I think ideally it would just try to measure from all of the directories that it finds. I don't think they will always be called reg_reg or outlier_removed.

**Comment by zhangfanmark** [comment]
So we will just remove that part and assume each subdirectory is one subject. Then, we may find a way to extract subject id from file name if arbitrary suffix is given. Now, we get the subject id by removing _reg and _outlier_removal from the file name. 

Regards,
Fan

**Comment by ljod** [comment]
ok. It's probably best not to remove the reg or the outlier removal. the goal is to keep the provenance information (what processing was done so far) as part of the subject ID.

**Pull request merged**
