### PR TITLE
Load measurement obtained for FiberTractScalarMeasurements module

### PR DESCRIPTION
**Pull request by zhangfanmark**
Hi @ljod ,

Could you take a look at the pull request? The code passed some initial tests but should be improved to handle other exceptions. Please let me know if we need to provide some other functionalities. Thanks! 

Regards,
Fan

### CODE REVIEW

**Comment by ljod** [comment]
Hi Fan. So far, this looks great. Before we merge, could you please add an example of how to use the output of your reader? It seems that the data are returned in a matrix and the user will need to know that the first row represents the measurement names/column headers. Perhaps it's an easier API if this could be slightly more processed, like if your class separates the headers and also the first column from the data itself. Also it's good if the data are stored as floats or doubles--glancing at the code I can't tell if this conversion was done or if they are strings. This is great to almost have a good way to get all the data into python!!

**Comment by zhangfanmark** [comment]
Sure, I'll add another test file for illustration and separate the headers and data. 
Also it would be good if we can extract the measurements using Python rather than Slicer module. I'll think of this later. For now, we can still keep using FiberTractScalarMeasurement. 

Thanks,
Fan

**Comment by ljod** [comment]
Hi Fan.

It would be ok to use python, but we prefer to use the Slicer module because it is generally useful for all users of Slicer and because the measurements are made with code that has been tested for years. So there’s no need to write a python tract measurement script.

LAuren


On Feb 11, 2016, at 11:55 AM, zhangfanmark <notifications@github.com<mailto:notifications@github.com>> wrote:


Sure, I'll add another test file for illustration and separate the headers and data.
Also it would be good if we can extract the measurements using Python rather than Slicer module. I'll think of this later. For now, we can still keep using FiberTractScalarMeasurement.

Thanks,
Fan

—
Reply to this email directly or view it on GitHub<https://github.com/ljod/whitematteranalysis/pull/33#issuecomment-182956824>.



The information in this e-mail is intended only for the person to whom it is
addressed. If you believe this e-mail was sent to you in error and the e-mail
contains patient information, please contact the Partners Compliance HelpLine at
http://www.partners.org/complianceline . If the e-mail was sent to you in error
but does not contain patient information, please contact the sender and properly
dispose of the e-mail.

**Comment by zhangfanmark** [comment]
Hi Lauren, could you take a look at the updates? Thanks!

Regards,
Fan

**Pull request merged**
